# Generated by Django 5.1.1 on 2024-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_video_call_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
