# Generated by Django 5.1.1 on 2024-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='items_in_cart',
            field=models.ManyToManyField(related_name='cart_set', to='api.product'),
        ),
    ]
