# Generated by Django 5.1.1 on 2024-09-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_items_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orders',
            field=models.ManyToManyField(related_name='order_set', to='api.product'),
        ),
    ]
